1- in control_plane_annotated.py
an error would occur while running experiment 4 that says:
"Traceback (most recent call last):
  File "control_plane.py", line 822, in <module>
    ratio = Poisoning_ratio[robust_type.split('_')[1]]
TypeError: list indices must be integers or slices, not str"

it was fixed by changing the line:
"ratio = Poisoning_ratio[robust_type.split('_')[1]]"
to:
"index_as_string = robust_type.split('_')[1]
ratio = Poisoning_ratio[int(index_as_string)]"
